# Site Settings
title: 두발로걷는개의 BLOG
email: ekfrl2815@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: ""

# User Settings
username: 두발로걷는개의 BLOG
user_description: Developer
disqus_username: 

# Social Media
# Remove the item if you don't need it
github_username: ekfrl2815@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
medium_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Project
    url: /project/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
